/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as OrdensServicoRouteImport } from './routes/ordens-servico'
import { Route as EventosFogoRouteImport } from './routes/eventos-fogo'
import { Route as EscalasRouteImport } from './routes/escalas'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as DespachosRouteImport } from './routes/despachos'
import { Route as CentroComandoRouteImport } from './routes/centro-comando'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResponderTerrestreIdRouteImport } from './routes/responder-terrestre.$id'
import { Route as ResponderMaquinarioIdRouteImport } from './routes/responder-maquinario.$id'
import { Route as ResponderAereoIdRouteImport } from './routes/responder-aereo.$id'
import { Route as OrdensServicoNovaRouteImport } from './routes/ordens-servico_.nova'
import { Route as OrdensServicoIdRouteImport } from './routes/ordens-servico_.$id'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensServicoRoute = OrdensServicoRouteImport.update({
  id: '/ordens-servico',
  path: '/ordens-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosFogoRoute = EventosFogoRouteImport.update({
  id: '/eventos-fogo',
  path: '/eventos-fogo',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasRoute = EscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const DespachosRoute = DespachosRouteImport.update({
  id: '/despachos',
  path: '/despachos',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroComandoRoute = CentroComandoRouteImport.update({
  id: '/centro-comando',
  path: '/centro-comando',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderTerrestreIdRoute = ResponderTerrestreIdRouteImport.update({
  id: '/responder-terrestre/$id',
  path: '/responder-terrestre/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderMaquinarioIdRoute = ResponderMaquinarioIdRouteImport.update({
  id: '/responder-maquinario/$id',
  path: '/responder-maquinario/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderAereoIdRoute = ResponderAereoIdRouteImport.update({
  id: '/responder-aereo/$id',
  path: '/responder-aereo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensServicoNovaRoute = OrdensServicoNovaRouteImport.update({
  id: '/ordens-servico_/nova',
  path: '/ordens-servico/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensServicoIdRoute = OrdensServicoIdRouteImport.update({
  id: '/ordens-servico_/$id',
  path: '/ordens-servico/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centro-comando': typeof CentroComandoRoute
  '/despachos': typeof DespachosRoute
  '/equipes': typeof EquipesRoute
  '/escalas': typeof EscalasRoute
  '/eventos-fogo': typeof EventosFogoRoute
  '/ordens-servico': typeof OrdensServicoRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/ordens-servico/$id': typeof OrdensServicoIdRoute
  '/ordens-servico/nova': typeof OrdensServicoNovaRoute
  '/responder-aereo/$id': typeof ResponderAereoIdRoute
  '/responder-maquinario/$id': typeof ResponderMaquinarioIdRoute
  '/responder-terrestre/$id': typeof ResponderTerrestreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centro-comando': typeof CentroComandoRoute
  '/despachos': typeof DespachosRoute
  '/equipes': typeof EquipesRoute
  '/escalas': typeof EscalasRoute
  '/eventos-fogo': typeof EventosFogoRoute
  '/ordens-servico': typeof OrdensServicoRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/ordens-servico/$id': typeof OrdensServicoIdRoute
  '/ordens-servico/nova': typeof OrdensServicoNovaRoute
  '/responder-aereo/$id': typeof ResponderAereoIdRoute
  '/responder-maquinario/$id': typeof ResponderMaquinarioIdRoute
  '/responder-terrestre/$id': typeof ResponderTerrestreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centro-comando': typeof CentroComandoRoute
  '/despachos': typeof DespachosRoute
  '/equipes': typeof EquipesRoute
  '/escalas': typeof EscalasRoute
  '/eventos-fogo': typeof EventosFogoRoute
  '/ordens-servico': typeof OrdensServicoRoute
  '/usuarios': typeof UsuariosRoute
  '/veiculos': typeof VeiculosRoute
  '/ordens-servico_/$id': typeof OrdensServicoIdRoute
  '/ordens-servico_/nova': typeof OrdensServicoNovaRoute
  '/responder-aereo/$id': typeof ResponderAereoIdRoute
  '/responder-maquinario/$id': typeof ResponderMaquinarioIdRoute
  '/responder-terrestre/$id': typeof ResponderTerrestreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/centro-comando'
    | '/despachos'
    | '/equipes'
    | '/escalas'
    | '/eventos-fogo'
    | '/ordens-servico'
    | '/usuarios'
    | '/veiculos'
    | '/ordens-servico/$id'
    | '/ordens-servico/nova'
    | '/responder-aereo/$id'
    | '/responder-maquinario/$id'
    | '/responder-terrestre/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/centro-comando'
    | '/despachos'
    | '/equipes'
    | '/escalas'
    | '/eventos-fogo'
    | '/ordens-servico'
    | '/usuarios'
    | '/veiculos'
    | '/ordens-servico/$id'
    | '/ordens-servico/nova'
    | '/responder-aereo/$id'
    | '/responder-maquinario/$id'
    | '/responder-terrestre/$id'
  id:
    | '__root__'
    | '/'
    | '/centro-comando'
    | '/despachos'
    | '/equipes'
    | '/escalas'
    | '/eventos-fogo'
    | '/ordens-servico'
    | '/usuarios'
    | '/veiculos'
    | '/ordens-servico_/$id'
    | '/ordens-servico_/nova'
    | '/responder-aereo/$id'
    | '/responder-maquinario/$id'
    | '/responder-terrestre/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentroComandoRoute: typeof CentroComandoRoute
  DespachosRoute: typeof DespachosRoute
  EquipesRoute: typeof EquipesRoute
  EscalasRoute: typeof EscalasRoute
  EventosFogoRoute: typeof EventosFogoRoute
  OrdensServicoRoute: typeof OrdensServicoRoute
  UsuariosRoute: typeof UsuariosRoute
  VeiculosRoute: typeof VeiculosRoute
  OrdensServicoIdRoute: typeof OrdensServicoIdRoute
  OrdensServicoNovaRoute: typeof OrdensServicoNovaRoute
  ResponderAereoIdRoute: typeof ResponderAereoIdRoute
  ResponderMaquinarioIdRoute: typeof ResponderMaquinarioIdRoute
  ResponderTerrestreIdRoute: typeof ResponderTerrestreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-servico': {
      id: '/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof OrdensServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos-fogo': {
      id: '/eventos-fogo'
      path: '/eventos-fogo'
      fullPath: '/eventos-fogo'
      preLoaderRoute: typeof EventosFogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas': {
      id: '/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof EscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despachos': {
      id: '/despachos'
      path: '/despachos'
      fullPath: '/despachos'
      preLoaderRoute: typeof DespachosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro-comando': {
      id: '/centro-comando'
      path: '/centro-comando'
      fullPath: '/centro-comando'
      preLoaderRoute: typeof CentroComandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder-terrestre/$id': {
      id: '/responder-terrestre/$id'
      path: '/responder-terrestre/$id'
      fullPath: '/responder-terrestre/$id'
      preLoaderRoute: typeof ResponderTerrestreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder-maquinario/$id': {
      id: '/responder-maquinario/$id'
      path: '/responder-maquinario/$id'
      fullPath: '/responder-maquinario/$id'
      preLoaderRoute: typeof ResponderMaquinarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder-aereo/$id': {
      id: '/responder-aereo/$id'
      path: '/responder-aereo/$id'
      fullPath: '/responder-aereo/$id'
      preLoaderRoute: typeof ResponderAereoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-servico_/nova': {
      id: '/ordens-servico_/nova'
      path: '/ordens-servico/nova'
      fullPath: '/ordens-servico/nova'
      preLoaderRoute: typeof OrdensServicoNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-servico_/$id': {
      id: '/ordens-servico_/$id'
      path: '/ordens-servico/$id'
      fullPath: '/ordens-servico/$id'
      preLoaderRoute: typeof OrdensServicoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentroComandoRoute: CentroComandoRoute,
  DespachosRoute: DespachosRoute,
  EquipesRoute: EquipesRoute,
  EscalasRoute: EscalasRoute,
  EventosFogoRoute: EventosFogoRoute,
  OrdensServicoRoute: OrdensServicoRoute,
  UsuariosRoute: UsuariosRoute,
  VeiculosRoute: VeiculosRoute,
  OrdensServicoIdRoute: OrdensServicoIdRoute,
  OrdensServicoNovaRoute: OrdensServicoNovaRoute,
  ResponderAereoIdRoute: ResponderAereoIdRoute,
  ResponderMaquinarioIdRoute: ResponderMaquinarioIdRoute,
  ResponderTerrestreIdRoute: ResponderTerrestreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
